name: SocialIOT
favicon: null
layout_spectrum: 0.6448232710827142
typography_spectrum: 0.1554742071311921
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2d2d2b'
    - '#fbfcfe'
    - '#8c6b4c'
    - '#006673'
    - '#84bcda'
  brandStrength: 0.875
  lightness: 0.3125
  saturation: 0.8125
  rhythmicContrast: 0.75
purpose: []
