name: SocialIOT
favicon: null
layout_spectrum: 0.70704
typography_spectrum: 0.1554742071311921
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2d2d2b'
    - '#fbfcfe'
    - '#8c6b4c'
    - '#006673'
    - '#84bcda'
  brandStrength: 0.4375
  lightness: 0.4375
  saturation: 0.25
  rhythmicContrast: 0.5
purpose: []
