name: SocialIOT
favicon: null
layout_spectrum: 0.70704
typography_spectrum: 0.1554742071311921
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#001017'
    - '#f1d8a0'
    - '#b5191c'
    - '#009084'
    - '#d07c60'
  brandStrength: 0.4375
  lightness: 0.625
  saturation: 0.25
  rhythmicContrast: 0.75
purpose: []
